### ISSUE TITLE
Online Help menu option broken

### ISSUE THREAD

**Issue by eseraygun** [GLSL-Debugger/GLSL-Debugger#51]
Help / Online Help menu option opens up URL http://www.vis.uni-stuttgart.de/glsldevil/ which returns 404.

**Comment by SirAnthony** [comment]
Thanks, can you make a PR?

**Comment by eseraygun** [comment]
I'm sorry, I thought I did. Here you go: https://github.com/GLSL-Debugger/GLSL-Debugger/pull/52
