### ISSUE TITLE
Could you please offer windows exe file?

### ISSUE THREAD

**Issue by gonnavis** [GLSL-Debugger/GLSL-Debugger#60]
Could you please offer windows exe file for people like me who don't know how to build?

**Comment by vvinycity** [comment]
If win32 is good enough for you, try glslDevil 1.1.4 (the old version of glsldb) which can be downloaded from http://glsldevil.software.informer.com/1.1/ (this link worked for me).
But if you need 64 bit version - it is a problem. AFAIK, even if you would build it, this code would not work in Win64 due to outdated disassembler in MHOOK library.

**Comment by napcode** [comment]
Sorry but it's rather unlikely. To my knowledge, mhook is unmaintained and, according to vvincity, doesn't work on Win64. Additionally, I've never built the debugger on windows. If someone else wants to step in an provide such a binary, I'd appreciate it.

**Comment by vvinycity** [comment]
Sorry, but what do you mean by "Sorry but it's rather unlikely"? Here is the relevant part of debug output:
DEBUG: Attaching SwapBuffers 0xffa09e68
mhooks: Mhook_SetHook: Started on the job: 000007FEFFA09E68 / 000007FEDBC6387D
mhooks: Mhook_SetHook: Started on the job: 000007FEFFA09E68 / 000007FEDBC89020
mhooks: DisassembleAndSkip: Disassembling 000007FEFFA09E68
mhooks: DisassembleAndSkip: 000007FEFFA09E68:             mov         qword ptr ss:[rsp+0x08], rbx
mhooks: Mhook_SetHook: disassembly signals 5 bytes
mhooks: SuspendOtherThreads: counted 0 other threads
mhooks: SuspendOtherThreads: Had a problem (or not running multithreaded), resuming all threads.
mhooks: TrampolineAlloc: Allocating for 000007FEFFA09E68 between 000007FE7FA19E68 and 000007FF7F989E68
mhooks: Find memory in allocated blocks
mhooks: Not found. Allocating new block
mhooks: TrampolineAlloc: Looking at address 000007FE7FA19E68
mhooks: TrampolineAlloc: Allocated block at 000007FE7FA20220 as the trampoline
mhooks: Mhook_SetHook: allocated structure at 000007FE7FA20220
mhooks: Mhook_SetHook: readwrite set on system function
mhooks: Mhook_SetHook: readwrite set on trampoline structure
mhooks: EmitJump: Jumping from 000007FE7FA20262 to 000007FEFFA09E6D, diff is 000000007FFE9C0B
mhooks: Mhook_SetHook: updated the trampoline
mhooks: EmitJump: Jumping from 000007FEFFA09E6D to 000007FEDBC89020, diff is 0000000023D80E4D
mhooks: Mhook_SetHook: Hooked the function!
DEBUG: Attaching glClearIndex 0xe2a2b7c0
mhooks: Mhook_SetHook: Started on the job: 000007FEE2A2B7C0 / 000007FEDBC63107
mhooks: Mhook_SetHook: Started on the job: 000007FEE2A2B7C0 / 000007FEDBC893F0
mhooks: DisassembleAndSkip: Disassembling 000007FEE2A2B7C0
mhooks: DisassembleAndSkip: 000007FEE2A2B7C0:             mov         eax, dword ptr cs:0x12B06[eip+ilen]=[0xE2A3E2CC]
mhooks: DisassembleAndSkip: found unsupported OP_IPREL on operand 1
mhooks: DisassembleAndSkip: instr byte 00: 0x8b
mhooks: DisassembleAndSkip: instr byte 01: 0x05
mhooks: DisassembleAndSkip: instr byte 02: 0x06
mhooks: DisassembleAndSkip: instr byte 03: 0x2b
mhooks: DisassembleAndSkip: instr byte 04: 0x01
mhooks: DisassembleAndSkip: instr byte 05: 0x00
mhooks: disassembly signals 0 bytes (unacceptable)
DEBUG: >>>> Mhook_SetHook(glClearIndex 0xe2a2b7c0 0xdbc63107) failed.
2017-11-27 17:26:15 [ERROR]::initLib.c:openEventsProc()::124: OpenEvent("1") failed: 2.INFO: DLL_PROCESS_DETACH
mhooks: Mhook_Unhook: 000007FEDC2B3190
DEBUG: Mhook_Unhook(SwapBuffers) failed.

So, if you would be kind enough to make sense of the above, and suggest the fix or some replacement for MHook' disassembler, I would gladly provide binaries, project in MSVC 2015 and sources to build glsldb with qt5.6.

**Comment by napcode** [comment]
Sorry for being unclear. I was referring to the first post. 
I don't have a fix or replacement for mhook or the disassembler.
