### ISSUE TITLE
MHook library does not work in Win64 environment

### ISSUE THREAD

**Issue by vvinycity** [GLSL-Debugger/GLSL-Debugger#61]
It seems that MHook library is outdated,  and it cannot be used in Wondows 64 bit. More precisely: the disassembler does not support X64 instruction set for modern Intel processors, as well as branches, etc. So, DisassembleAndSkip fails and the whole application does not even start.  Is there any new version of MHook that works in X64 environment?

**Comment by vvinycity** [comment]
I have to repeat my comment here, because the issue where I put it originally became closed.
Here is the relevant part of "debug output" of attachTrampolines() loop:

 DEBUG: Attaching SwapBuffers 0xffa09e68
 mhooks: Mhook_SetHook: Started on the job: 000007FEFFA09E68 / 000007FEDBC6387D
 mhooks: Mhook_SetHook: Started on the job: 000007FEFFA09E68 / 000007FEDBC89020
 mhooks: DisassembleAndSkip: Disassembling 000007FEFFA09E68
 mhooks: DisassembleAndSkip: 000007FEFFA09E68: mov qword ptr ss:[rsp+0x08], rbx
 mhooks: Mhook_SetHook: disassembly signals 5 bytes
 mhooks: SuspendOtherThreads: counted 0 other threads
 mhooks: SuspendOtherThreads: Had a problem (or not running multithreaded), resuming all threads.
 mhooks: TrampolineAlloc: Allocating for 000007FEFFA09E68 between 000007FE7FA19E68 and 000007FF7F989E68
 mhooks: Find memory in allocated blocks
 mhooks: Not found. Allocating new block
 mhooks: TrampolineAlloc: Looking at address 000007FE7FA19E68
 mhooks: TrampolineAlloc: Allocated block at 000007FE7FA20220 as the trampoline
 mhooks: Mhook_SetHook: allocated structure at 000007FE7FA20220
 mhooks: Mhook_SetHook: readwrite set on system function
 mhooks: Mhook_SetHook: readwrite set on trampoline structure
 mhooks: EmitJump: Jumping from 000007FE7FA20262 to 000007FEFFA09E6D, diff is 000000007FFE9C0B
 mhooks: Mhook_SetHook: updated the trampoline
 mhooks: EmitJump: Jumping from 000007FEFFA09E6D to 000007FEDBC89020, diff is 0000000023D80E4D
 mhooks: Mhook_SetHook: Hooked the function!
 DEBUG: Attaching glClearIndex 0xe2a2b7c0
 mhooks: Mhook_SetHook: Started on the job: 000007FEE2A2B7C0 / 000007FEDBC63107
 mhooks: Mhook_SetHook: Started on the job: 000007FEE2A2B7C0 / 000007FEDBC893F0
 mhooks: DisassembleAndSkip: Disassembling 000007FEE2A2B7C0
 mhooks: DisassembleAndSkip: 000007FEE2A2B7C0: mov eax, dword ptr cs:0x12B06[eip+ilen]=[0xE2A3E2CC]
 mhooks: DisassembleAndSkip: found unsupported OP_IPREL on operand 1
 mhooks: DisassembleAndSkip: instr byte 00: 0x8b
 mhooks: DisassembleAndSkip: instr byte 01: 0x05
 mhooks: DisassembleAndSkip: instr byte 02: 0x06
 mhooks: DisassembleAndSkip: instr byte 03: 0x2b
 mhooks: DisassembleAndSkip: instr byte 04: 0x01
 mhooks: DisassembleAndSkip: instr byte 05: 0x00
 mhooks: disassembly signals 0 bytes (unacceptable)
 DEBUG: >>>> Mhook_SetHook(glClearIndex 0xe2a2b7c0 0xdbc63107) failed.
 2017-11-27 17:26:15 [ERROR]::initLib.c:openEventsProc()::124: OpenEvent("1") failed: 2.INFO: DLL_PROCESS_DETACH
 mhooks: Mhook_Unhook: 000007FEDC2B3190
 DEBUG: Mhook_Unhook(SwapBuffers) failed.

As we know, SwapBuffers is the first, and glClearIndex is the second from a list of more than 2000 OpenGL functions. If you absorb the first error somehow, the loop would fail after a while with another condition on another function, etc. 
So, if anyone would be kind enough to make sense of the above, and provide proven fix or some replacement for MHook' disassembler (which will fork with current Intel processors), I would gladly provide in return the binaries, source patches and the project in MSVC 2015 to build glsldb with qt5.6 in WIn64.

**Comment by SirAnthony** [comment]
[This](https://github.com/apriorit/mhook) fork of a fork seems most recent. Can you check if this library work?

**Comment by vvinycity** [comment]
Thank you for this information. I am building with this version presently.

**Comment by vvinycity** [comment]
No, unfortunately this version did not make any difference. It required minor changes, like

std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> convert;
std::wstring description = convert.from_bytes(pins->String); 

//ODPRINTF((L"mhooks: DisassembleAndSkip: %p:(0x%2.2x) %s", pLoc, pins->Length, pins->String));
ODPRINTF((L"mhooks: DisassembleAndSkip: %p:(0x%2.2x) %s", pLoc, pins->Length, description.c_str())); // vvi 

to create readable debug output, but otherwise it is practically identical to prior version. By the way, incorrect debug output makes me think that this version was never tested in Win64, otherwise they would see the messy string on the screen and fix it.

**Comment by XenonofArcticus** [comment]
It looks like that fork is at least actively being used and developed, so perhaps the most recent committer could help you if you reached out to him.

**Comment by vvinycity** [comment]
Perhaps they should be more specific with saying where it was tested, and where it wasn't. Sorry, I cannot spend any more time with this. By the way, NVIDIA's Nsight is free and it works. Actually, the resent release (5.4) is very impressive.
